### ISSUE TITLE
运行后无法连接

### ISSUE THREAD

**Issue by zmackey** [tx991020/rustdesk-server-demo#2]
编译运行后客户端无法连接到server
![20220508041430](https://user-images.githubusercontent.com/53858118/167270435-7cd05213-05b9-4881-a8a8-71a8f51d0881.png)

**Comment by zmackey** [comment]
抓包看 server端只收不发

**Comment by shieruyu** [comment]
你得改rustdesk 的代码把config里面 ip地址改成这个服务端的地址啊

**Comment by shieruyu** [comment]
rustdesk 是tcp 通讯不合适，，推荐用这个https://github.com/livekit ，我自己开发的远程桌面也是基于这个。这个是webrtc通讯

**Comment by zmackey** [comment]
客户端改过ip 测试的， 你说livekit 我有时间瞅瞅。谢谢
